# Generated by Django 5.0.6 on 2025-04-20 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('target_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('UPCOMING', 'Coming Soon'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('ZAKAH', 'Zakah'), ('SADAQA', 'Sadaqa'), ('PROJECTS', 'Projects')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='date_contributed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contributioncounter',
            name='contribution_type',
            field=models.CharField(choices=[('ZAKAH', 'Zakah'), ('SADAQA', 'Sadaqa'), ('PROJECTS', 'Projects')], max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.project'),
        ),
    ]
