# Generated by Django 5.0.6 on 2025-04-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_project_alter_contribution_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('ZAKAH', 'Zakah'), ('SADAQA', 'Sadaqa'), ('FITRA', 'Fitra'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contributioncounter',
            name='contribution_type',
            field=models.CharField(choices=[('ZAKAH', 'Zakah'), ('SADAQA', 'Sadaqa'), ('FITRA', 'Fitra'), ('OTHER', 'Other')], max_length=10, unique=True),
        ),
    ]
