# Generated by Django 5.0.6 on 2025-04-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakahNisab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zakah Nisab',
                'verbose_name_plural': 'Zakah Nisab',
            },
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='name',
        ),
        migrations.AddField(
            model_name='contribution',
            name='first_name',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='last_name',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
    ]
