# Generated by Django 5.0.6 on 2025-04-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_zakahnisab_remove_contribution_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='number_of_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='zakah_type',
            field=models.CharField(blank=True, choices=[('MAAL', 'Zakah al-Maal'), ('FITRI', 'Zakah al-Fitr')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('ZAKAH', 'Zakah'), ('SADAQA', 'Sadaqa'), ('PROJECTS', 'Projects')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='receipt_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contributioncounter',
            name='contribution_type',
            field=models.CharField(choices=[('ZAKAH', 'Zakah'), ('SADAQA', 'Sadaqa'), ('PROJECTS', 'Projects')], max_length=10, unique=True),
        ),
    ]
