# Generated by Django 5.0.6 on 2025-04-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_contribution_number_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('ZAKAH', 'Zakah'), ('SADAQA', 'Sadaqa'), ('FITRA', 'Fitra'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contributioncounter',
            name='contribution_type',
            field=models.CharField(choices=[('ZAKAH', 'Zakah'), ('SADAQA', 'Sadaqa'), ('FITRA', 'Fitra'), ('OTHER', 'Other')], max_length=10, unique=True),
        ),
    ]
