# Generated by Django 5.0.6 on 2025-05-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_contribution_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
