# Generated by Django 5.0.6 on 2025-05-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.district'),
        ),
    ]
